services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: film_data
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql
